Creating a new branch is quick AND simple.
test branch dev is Ok?
Git is a free software ...

Now is work on branch dev, But I find a Bug for number issue-101
kaimilu work is on branch kaimilu for company......